Hivemind/Hivemind/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jumia.urls')),
    path('inbox/', include('chart.urls')),
    path('cart/', include('cart.urls')),
    path('account/', include('user.urls')),
    path('order/', include('orders.urls')),
    path('business/', include('business.urls')),

    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Hivemind/business/urls.py
from django.urls import path
from .views import *
from django.contrib.auth.views import *

app_name = 'business'

urlpatterns = [
    path('', manage, name='manage'),
    path('detail/<int:id>',detail, name= 'detail'),
    path('orders/',orders, name= 'ordered'),
    path('order-details/<int:id>',order_details, name= 'order_details'),
    path('products/', business_reg, name='reg'),
    path('inbox/',inbox, name='inbox'),
    path('<int:pk>/',cdetail, name='cdetail'),
]

Hivemind/cart/urls.py
from django.urls import path 
from . import views

app_name = 'cart'

urlpatterns = [    
    path('', views.cart_detail, name='cart_detail'),
    path('update/<int:product_id>', views.cart_update, name='cart_update'),    
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),    
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'), ]

Hivemind/jumia/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth.views import *
from .sitemap import StaticViewSitemap
from django.contrib.sitemaps.views import sitemap

sitemap_dict = {
    "static": StaticViewSitemap(),
}

app_name = 'jumia'

urlpatterns = [
    path('', items, name='items'),
    path('sitemap.xml', sitemap, {"sitemaps": sitemap_dict}, name="django.contrib.sitemaps.views.sitemap"),
    path('detail/<int:id>', detail, name='detail'),
    path('category/<int:id>', categories, name='category'),
    path('results/', search, name='search'),
]

Hivemind/orders/urls.py
from django.urls import path 
from .views import *

app_name = 'orders'

urlpatterns = [
    path('created/', order_create, name='order_create'),
    path('direct/<int:item_id>/',direct_order, name='direct_order'),
    path('orders/', orders, name='order'),
    path('order-details/<int:id>', order_details, name='detail'),
    path('order-delete/<int:id>/delete', delete_order, name='delete_order'),
    path('payment/<int:order_id>/', initiate_payment, name='payment'),
    path('success/', payment_callback, name='payment_callback'),
]

Hivemind/business/models.py
from django.db import models
from user.models import User
from django.utils import timezone

class Business(models.Model):
    user = models.OneToOneField(User, on_delete= models.CASCADE)
    username = models.CharField(max_length=100, null=True)
    email = models.CharField(max_length=100, null=True)
    phone_number = models.CharField(max_length=100, null=True)
    created_at = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        """Returns a string representation of the business."""
        return self.username if self.username else 'not registered'

Hivemind/business/forms.py
from django import forms
from .models import Business
from django.contrib.auth.forms import UserCreationForm
from user.models import User
from django.db import transaction
from chart.models import ConversationMessage

class BusinessForm(forms.ModelForm):
    class Meta:
        model = Business
        fields = '__all__'



class BusinessSignUpForm(UserCreationForm):    
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('username', 'email', 'password1', 'password2')
        
  

    @transaction.atomic
    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_business = True
        if commit:
            user.save()
        business = Business.objects.create(user=user, username=self.cleaned_data.get('username'), email=self.cleaned_data.get('email'), phone_number=self.cleaned_data.get('phone_number'))
        return user
    
class ConversationMessageForm(forms.ModelForm):
    class Meta:
        model = ConversationMessage
        fields = ('content',)
        widgets = {
            'content': forms.Textarea(attrs={
                'class': 'w-full py-4 px-6 rounded-xl border'
            })
        }

Hivemind/orders/forms.py
from django import forms 
from .models import Order


class OrderCreateForm(forms.ModelForm):   
    class Meta:        
        model = Order        
        fields = ['address', 'phone_number']
        widgets = {
            'address': forms.TextInput(attrs={'id':'address','placeholder': 'Delivery address','class': 'w-full py-1 lg:py-2 px-3 rounded-lg lg:rounded-xl border border-red-900 autocomplete-container'}),
            'phone_number': forms.TextInput(attrs={'placeholder': 'Number will be used to intiate payments and calls.','class': 'w-full py-1 lg:py-22 px-3 rounded-lg lg:rounded-xl border border-red-900'}),
    
        }

Hivemind/business/views.py
from django.shortcuts import render,redirect, get_object_or_404
from user.decorators import customer_required, business_required
from django.contrib.auth.decorators import login_required
from .forms import BusinessForm
from .models import Business
from jumia.models import Type
from orders.models import OrderItem, Order
from .forms import ConversationMessageForm
from chart.models import Conversation
from user.models import User, Customer

def about(request):
    return render(request, 'bus/about.html' )

@business_required
def sell(request):
    business = Business.objects.all()
    return render(request, 'bus/board.html', {'business':business} )

def business_reg(request):
    if request.method == 'POST':
        form = BusinessForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('business:sell')
    else:
        form = BusinessForm()

    return render(request, 'bus/bus_reg.html', {'form':form})

@business_required
def manage(request):
    items = Type.objects.all()
    return render(request, 'bus/manage.html', {'items': items} )


@business_required
@login_required
def detail(request, id):
    item = get_object_or_404(Type, pk=id)
    related_items = Type.objects.filter(category=item.category).exclude(pk=id)

    return render(request, 'bus/detail.html', {
        'item': item,
        'related_items': related_items,
    })

@business_required
def orders(request):
    orders = Order.objects.all()
    return render(request, 'bus/orders.html', {'orders':orders,})

@business_required
def order_details(request, id):
    orders = Order.objects.filter(id=id).first()
    product = OrderItem.objects.filter(order=orders)
    return render(request, 'bus/ordered.html', {'orders':orders, 'product':product})


@login_required
def inbox(request):
    conversations = Conversation.objects.filter(members__in=[request.user.id])

    return render(request, 'bus/inbox.html', {
        'conversations': conversations
    })

@login_required
def cdetail(request, pk):
    conversation = Conversation.objects.filter(members__in=[request.user.id]).get(pk=pk)

    if request.method == 'POST':
        form = ConversationMessageForm(request.POST)

        if form.is_valid():
            conversation_message = form.save(commit=False)
            conversation_message.conversation = conversation
            conversation_message.created_by = request.user
            conversation_message.save()

            conversation.save()

            return redirect('business:cdetail', pk=pk)
    else:
        form = ConversationMessageForm()

    return render(request, 'bus/cdetail.html', {
        'conversation': conversation,
        'form': form
    })

Hivemind/orders/views.py
from django.shortcuts import render,get_object_or_404, redirect
from .models import OrderItem , Order
from django.http import HttpResponse, HttpResponseBadRequest
from .forms import OrderCreateForm
from cart.cart import Cart
from django.contrib.auth.decorators import login_required
from user.decorators import customer_required
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from twilio.rest import Client
import requests
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from .models import Payment, Order
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from .models import Payment
import re 
from user.models import Customer
from jumia.models import Type

@customer_required
def order_create(request):  
    user = request.user
    if user.is_authenticated:
        customer = Customer.objects.get(user=user)
        cart = Cart(request)
        if request.method == 'POST':      
            form = OrderCreateForm(request.POST)
            if form.is_valid():
                order = form.save(commit=False)
                order.user = request.user  
                order = form.save()     
                
                accountSID = 'ACe6d928ec56d8f0c7bce4f4301f592d45'
                authToken = '59519c547005d51047167550327627e5'
                twilioCli = Client(accountSID, authToken)
                myTwilioNumber = '+13345083970'
                myCellPhone = '+256761420297'
                twilioCli.messages.create(
                    body=f'Order was created by {customer.first_name} {customer.last_name}.\nFollow url to see details https://piusDev.pythonanywhere.com/business/orders/', 
                    from_=myTwilioNumber, 
                    to=myCellPhone
                    )
                
                for item in cart:                
                    OrderItem.objects.create(order=order, product=item['product'], price=item['price'],quantity=item['quantity'])        
                cart.clear()
            return render(request,'order/created.html', {'order': order})    
        else:        
            form = OrderCreateForm()    
        return render(request, 'jumia/checkout.html',{'cart': cart,'form': form,'customer':customer})

@login_required
def delete_order(request,id):
    delete_order = get_object_or_404(Order, id=id)

    if delete_order.user != request.user:
        return HttpResponseBadRequest("You do not have permission to delete this order.")

    if request.method == 'POST':
        delete_order.delete()
        return redirect('orders:order')
        
@customer_required
def orders(request):
    customer = Customer.objects.get(user=request.user)
    orders = Order.objects.filter(user=request.user)
    return render(request, 'order/orders.html', {'orders':orders,'customer':customer})

@customer_required
def order_details(request, id):
    orders = Order.objects.filter(id=id).filter(user=request.user).first()
    product = OrderItem.objects.filter(order=orders)
    return render(request, 'order/order_details.html', {'orders':orders, 'product':product})


def initiate_payment(request, order_id):
    phone_exp = re.compile(r'^(0)(\d{9})$')
    intl_phone_exp = re.compile(r'^\+256(\d{9})$')

    if request.method == 'POST':
        url = 'https://www.easypay.co.ug/api/'
        secret = 'd58fadc8a79ed090'
        client_id = '317caec39c6e050c'
        
        order = get_object_or_404(Order, id=order_id)
        amount = int(order.cost())
        
        # Format phone number
        phone_number = str(order.phone_number)
        
        match = phone_exp.match(phone_number)
        if match:
            phone_number = '+256' + match.group(2)  # Replace '0' with '+256'
        elif not intl_phone_exp.match(phone_number):
            return JsonResponse({'status': 'error', 'message': 'Invalid phone number format'})

        try:
            payload = {
                "username": client_id,
                "password": secret,
                "action": "mmdeposit",
                'amount': amount,
                'currency': 'UGX',
                'phone': phone_number,
                'reference': f'order_{order.id}'
            }
            headers = {
                'Content-Type': 'application/json'
            }

            response = requests.post(url, json=payload, headers=headers)

            data = response.json()
            if response.status_code == 200 and data.get('success'):
                Payment.objects.create(order=order, amount=amount, status='Pending', transaction_id=data['transaction_id'])
                return JsonResponse({'status': 'success', 'transaction_id': data['transaction_id']})
            else:
                error_message = data.get('errormsg', 'Unknown error occurred')
                return JsonResponse({'status': 'error', 'message': error_message})
        except Exception as e:
            return JsonResponse({'success': False, 'errormsg': str(e)})
    
    return JsonResponse({'success': False, 'errormsg': 'Invalid request method'})

    
@csrf_exempt
def payment_callback(request):
    if request.method == 'POST':
        data = request.json()
        transaction_id = data.get('transaction_id')
        status = data.get('status')

        payment = Payment.objects.get(transaction_id=transaction_id)
        payment.status = status
        payment.save()

        if status == 'Completed':
            # Update order status, notify customer, etc.
            pass

        return JsonResponse({'status': 'success'})

    return JsonResponse({'status': 'error'}, status=400)

@customer_required
def direct_order(request, item_id):
    item = get_object_or_404(Type, id=item_id)
    user = request.user
    if user.is_authenticated:
        customer = Customer.objects.get(user=user)
        if request.method == 'POST':
            form = OrderCreateForm(request.POST)
            if form.is_valid():
                order = form.save(commit=False)
                order.user = request.user  
                order.save()
                
                accountSID = 'ACe6d928ec56d8f0c7bce4f4301f592d45'
                authToken = '59519c547005d51047167550327627e5'
                twilioCli = Client(accountSID, authToken)
                myTwilioNumber = '+13345083970'
                myCellPhone = '+256761420297'
                twilioCli.messages.create(
                    body=f'Order was created by {customer.first_name} {customer.last_name}.\nFollow url to see details https://piusDev.pythonanywhere.com/business/orders/', 
                    from_=myTwilioNumber, 
                    to=myCellPhone
                                          )
                
                order_item = OrderItem(
                    order=order,
                    product=item,
                    price=item.price,
                    quantity=request.POST.get('quantity', 1)
                )
                order_item.save()
                return render(request,'order/created.html', {'order': order})
        else:
            form = OrderCreateForm()

        return render(request, 'jumia/detail.html', {'form': form, 'item': item})
    else:
        return redirect('user:login')

Hivemind/business/templates/bus/bus_reg.html
{% extends 'user/base.html' %}

{% block title %}Sign up{% endblock %}
{% load static %}
{% block content %}
<br>
<br>
<br>
<section class="signup">
  <div class="container">
      <div class="signup-content">
          <div class="signup-form">
              <h2 class="form-title">Sign up</h2>
              <form action=" . " method="POST" class="register-form" id="register-form">
                {% csrf_token %}
                  <div class="form-group">
                    <label for="lname"><i class="zmdi zmdi-account material-icons-name"></i></label>
                    {{form.username}}
                  </div>
                  <div class="form-group">
                      <label for="email"><i class="zmdi zmdi-email"></i></label>
                      {{form.email}}
                  </div>
                  <div class="form-group">
                    <label for="name"><i class="zmdi zmdi-phone"></i></label>
                    {{form.phone_number}}
                  </div>
                  <div class="form-group">
                      <label for="pass"><i class="zmdi zmdi-lock"></i></label>
                      {{form.password1}}
                  </div>
                  <div class="form-group">
                      <label for="re-pass"><i class="zmdi zmdi-lock-outline"></i></label>
                      {{form.password2}}
                  </div>
                  <div class="form-group">
                    <a href="#">I have an account</a>
                  </div>
                  <div class="form-group form-button">
                      <input type="submit" name="signup" id="signup" class="form-submit" value="Register"/>
                  </div>
              </form>
          </div>
          <div class="signup-image">
              <figure><img src="{%static 'reg/images/signup-image.jpg' %}" alt="sing up image"></figure>
          </div>
      </div>
  </div>
</section>
{% endblock %}

Hivemind/business/templates/bus/cdetail.html
{% extends 'bus/board.html' %}

{% block title %}Conversation{% endblock %}

{% block content %}
<h1 class="mb-6 text-3xl">Conversation</h1>

<div class="space-y-6">
    {% for message in conversation.messages.all %}
        <div class="p-6 flex {% if message.created_by == request.user %}bg-blue-100{% else %}bg-gray-100{% endif %} rounded-xl">
            <div>
                <p class="mb-4"><strong>{{ message.created_by.username }}</strong> @ {{ message.created_at }}</p>
                <p>{{ message.content }}</p>
            </div>
        </div>
    {% endfor %}
</div>

<form method="post" action="." class="mt-6">
    {% csrf_token %}

    {{ form.as_p }}

    <button class="btn btn-block btn-success my-3 py-3 font-semibold">Send</button>
</form>
{% endblock %}

Hivemind/business/templates/bus/detail.html
{% extends 'bus/board.html' %}

{% block title %}{{ item.name }}{% endblock %}

{% block content %}
<div class="grid grid-cols-5 gap-6">
    <div class="col-span-2">
        <img src="{{ item.image.url }}" class=" h-30 rounded-xl">
    </div>

    <div class="col-span-3 p-6 bg-gray-100 rounded-xl">
        <h1 class="mb-6 text-3xl">{{ item.name }}</h1>
        <p class="text-gray-500"><strong>Price: </strong>{{ item.price }}</p>
    
        {% if item.description %}
            <p class="text-gray-700">
                <strong class="text-gray-500">Description:</strong><br>
                {{ item.description }}
            </p>
        {% endif %}
        <div>
            <a href="" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-green-500 text-white rounded-xl">Edit</a>
            <a href="" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">Delete</a>
            <a href="" class="inline-block mt-6 px-6 py-3 text-lg font-semibold bg-red-500 text-white rounded-xl">View messages</a>
        </div>
    </div>
</div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Related items</h2>

    <div class="grid grid-cols-3 gap-3">
        {% for item in related_items %}
            <div>
                <a href="{% url 'business:detail' item.id %}">
                    <div>
                        <img src="{{ item.image.url }}" class="rounded-t-xl">
                    </div>

                    <div class="p-6 bg-white rounded-b-xl">
                        <h2 class="text-2xl">{{ item.name }}</h2>
                        <p class="text-gray-500">Price: {{ item.price }}</p>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

Hivemind/business/templates/bus/manage.html
{% extends 'bus/board.html' %}

{% block title %}Manage{% endblock %}
{% load humanize %}

{% block content %}
<h2 class="md:text-2xl lg:text-3xl flex justify-center text-xl font-bold mt-5 text-gray-800">Products on Sale</h2>

<div class="grid grid-cols-2 md:grid-cols-2 lg:grid-cols-4 gap-5">
  {% for item in items %}
  <div class="mt-2 relative group">
    <div class="rounded-2xl overflow-hidden shadow-md relative transform transition-transform duration-300 hover:scale-105 hover:shadow-xl">
      <a href="{% url 'business:detail' item.pk %}" class="transition ease-in-out duration-700">
        <img src="{{item.image.url}}" alt="" class="w-full h-48 object-cover bg-gray-100 mt-2 rounded-2xl transition-transform duration-300 group-hover:scale-110">
      </a>
      <!-- <div class="bg-yellow-300 text-secondary-200 text-sm uppercase font-bold rounded-t-none rounded-b-2xl p-2 absolute top-0 right-0 mb-2 mr-2">
        <span>-40%</span>
      </div> -->
      <div class="text-white font-bold bg-gray-900 bg-opacity-50 px-3 rounded-lg absolute bottom-0 left-0 mb-2 ml-2">
        <span>{{item.category}}</span>
      </div>
    </div>
    <div class="lg:mt-2">
      <h5 class="text-lg lg:text-xl font-bold text-gray-800">{{item.name}}</h5>
    </div>
  </div>
  {% endfor %}
</div>
{% endblock %}

Hivemind/business/templates/bus/ordered.html
{% extends 'bus/board.html' %}

{% block title %} Orders {% endblock %}
{% load humanize %}
{% block content %}
<div class="lg:hidden">
  <h1 class="text-start text-lg font-semibold py-2 ml-2">Order summary</h1>
  <div class="border max-w-lg rounded-lg shadow-sm bg-white">
    <div class="flex justify-between">
      <h1 class="text-sm font-semibold pt-2 ml-2">Date: </h1>
      <h1 class="text-sm font-semibold pt-2 mr-1">{{orders.created}}</h1>
    </div>
    <div class="flex justify-between">
      <h1 class="text-sm font-semibold ml-2">Phone Number: </h1>
      <h1 class="text-sm font-semibold mr-1">{{orders.phone_number}}</h1>
    </div>
    <div class="flex justify-between mb-2">
      <h1 class="text-sm font-semibold ml-2">{{orders.address}}</h1>
    </div>
  </div>
  <h1 class="text-start text-lg font-semibold py-2 ml-2">Products</h1>
  {% for item in product %}     
  <div class="border p-3 bg-white">
    <div class="flex flex-col lg:flex-row justify-between">
        <div class="flex inline-block">
            <img class="rounded-lg" src="{{item.product.image.url}}" alt="{{item.product.name}}" style="max-width: 100px;max-height: 100px">
            <div class="block">
                <h1 class="text-md lg:text-lg px-3">{{item.product.name}} | <span class="text-sm"><a href="{% url 'jumia:category' item.product.category.id%}">{{item.product.category}}</a></span></h1>
                <h1 class="text-sm lg:text-lg px-3">Quantity: {{item.quantity}}</h1>
                <div class="block">
                    <h1 class="text-lg font-semibold px-3">UGX {{item.get_cost|intcomma}}</h1>
                </div>
            </div>
        </div>
    </div>
  </div>    
  {% endfor %}
  <h1 class="text-start text-lg font-semibold py-2 ml-2">Totals</h1>
  <div class="border shadow-sm p-2 rounded-lg lg:rounded-xl bg-white lg:hidden">
    <h1 class="flex justify-between font-semibold">Items Total: <span>UGX {{orders.get_total_cost|intcomma}}</span></h1>
    <h1 class="flex justify-between font-semibold pt-2 pb-1">Delivery: <span>UGX {{orders.delivery|intcomma}}</span></h1>
    <hr>
    <h1 class="flex justify-between font-bold pt-3">Total: <span class="text-xl">UGX {{orders.cost|intcomma}}</span></h1>
</div>
</div>

<div class="hidden lg:grid lg:grid-cols-12 gap-5 mt-4">
  <div class="lg:col-span-9 border shadow-md">
      <h1 class="text-start text-xl font-bold p-2">Ordered Products </h1>
      <hr class="w-full">
      <div class="grid grid-cols-3 gap-5 p-3">
          {% for item in product %}     
          <div class="flex flex-col lg:flex-row justify-between">
            <div class="flex inline-block">
                <img class="rounded-lg" src="{{item.product.image.url}}" alt="{{item.product.name}}" style="max-width: 100px;max-height: 100px">
                <div class="block pl-2">
                    <h1 class="text-md lg:text-lg">{{item.product.name}} | <span class="text-lg"><a href="{% url 'jumia:category' item.product.category.id%}">{{item.product.category}}</a></span></h1>
                    <h1 class="text-sm lg:text-lg">Quantity: {{item.quantity}}</h1>
                    <h1 class="text-lg font-semibold">UGX {{item.get_cost|intcomma}}</h1>
                </div>
            </div>
          </div>     
          {% endfor %}
      </div>
  </div>
  <div class="hidden lg:block lg:col-span-3 lg:mt-3 border shadow-md p-2 h-48">
      <h1 class="text-start font-bold text-xl">ORDER TOTALS</h1>
      <hr>
      <div class="flex justify-between font-semibold">
        <p class="text-lg">Items Total: </p>
        <h1 class="text-lg">UGX {{ orders.get_total_cost|intcomma }}</h1>
      </div>
      <div class="flex justify-between font-semibold">
        <p class="text-lg">Delivery: </p>
        <h1 class="text-lg">UGX {{ orders.delivery|intcomma }}</h1>
      </div>
      <hr class="p-1">
      <div class="flex justify-between mb-2">
          <p class="text-lg font-semibold">Total: </p>
          <h1 class="text-xl font-bold">UGX {{ orders.cost|intcomma }}</h1>
      </div>
  </div>    
</div>

<div class="hidden lg:block">
  <div class="border max-w-lg rounded-lg shadow-sm mt-3 mr-2">
    <h1 class="text-start text-xl font-semibold pt-2 ml-2">Order summary</h1>
    <hr>
    <div class="flex justify-between">
      <h1 class="text-md font-semibold pt-2 ml-2">Date: </h1>
      <h1 class="text-sm font-semibold pt-3 mr-1">{{orders.created}}</h1>
    </div>
    <div class="flex justify-between">
      <h1 class="text-md font-semibold ml-2">Phone Number: </h1>
      <h1 class="text-sm font-semibold mr-1">{{orders.phone_number}}</h1>
    </div>
    <div class="flex justify-between mb-2">
      <h1 class="text-md font-semibold ml-2">Address: </h1>
      <h1 class="text-sm font-semibold">{{orders.address}}</h1>
    </div>
  </div>
</div>
{% endblock %}

Hivemind/business/templates/bus/orders.html
{% extends 'bus/board.html' %}

{% block title %}Orders{% endblock %}

{% block content %}
<div class="container py-4">
    <h1 class="flex text-start text-xl lg:text-4xl font-bold text-gray-800 mb-2">Customer Orders</h1>
    <hr class="mb-8">

    <div class="row px-2">
        {% if orders %}
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {% for order in orders %}
            <a href="{% url 'business:order_details' order.id %}" class="block transition transform hover:scale-105 bg-white">
                <div class="border border-gray-100 shadow-md rounded-xl p-6 hover:bg-gray-50">
                    <div class="text-green-500 mb-1">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="inline-block w-5 mb-2">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M11.35 3.836c-.065.21-.1.433-.1.664 0 .414.336.75.75.75h4.5a.75.75 0 0 0 .75-.75 2.25 2.25 0 0 0-.1-.664m-5.8 0A2.251 2.251 0 0 1 13.5 2.25H15c1.012 0 1.867.668 2.15 1.586m-5.8 0c-.376.023-.75.05-1.124.08C9.095 4.01 8.25 4.973 8.25 6.108V8.25m8.9-4.414c.376.023.75.05 1.124.08 1.131.094 1.976 1.057 1.976 2.192V16.5A2.25 2.25 0 0 1 18 18.75h-2.25m-7.5-10.5H4.875c-.621 0-1.125.504-1.125 1.125v11.25c0 .621.504 1.125 1.125 1.125h9.75c.621 0 1.125-.504 1.125-1.125V18.75m-7.5-10.5h6.375c.621 0 1.125.504 1.125 1.125v9.375m-8.25-3 1.5 1.5 3-3.75" />
                        </svg>
                        <h2 class="text-sm font-bold inline-block">Order ID: {{ order.id }}</h2>
                    </div>
                    <div class="text-sm text-gray-700">
                        <p><strong>Name:</strong> {{ order.user.customer.first_name }} {{ order.user.customer.last_name }}</p>
                        <p><strong>Date:</strong> {{ order.created }}</p>
                        <p><strong>Address:</strong> {{ order.address }}</p>
                    </div>
                </div>
            </a>
            {% endfor %}
        </div>
        {% else %}
        <div class="col-12 text-center font-mono">
            <h3 class="py-2 text-lg lg:text-2xl text-gray-700">No orders from customers yet!!</h3>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}