Hivemind/Hivemind/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jumia.urls')),
    path('inbox/', include('chart.urls')),
    path('cart/', include('cart.urls')),
    path('account/', include('user.urls')),
    path('order/', include('orders.urls')),
    path('business/', include('business.urls')),

    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Hivemind/cart/urls.py
from django.urls import path 
from . import views

app_name = 'cart'

urlpatterns = [    
    path('', views.cart_detail, name='cart_detail'),
    path('update/<int:product_id>', views.cart_update, name='cart_update'),    
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),    
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'), ]

Hivemind/jumia/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth.views import *
from .sitemap import StaticViewSitemap
from django.contrib.sitemaps.views import sitemap

sitemap_dict = {
    "static": StaticViewSitemap(),
}

app_name = 'jumia'

urlpatterns = [
    path('', items, name='items'),
    path('sitemap.xml', sitemap, {"sitemaps": sitemap_dict}, name="django.contrib.sitemaps.views.sitemap"),
    path('detail/<int:id>', detail, name='detail'),
    path('category/<int:id>', categories, name='category'),
    path('results/', search, name='search'),
]

Hivemind/orders/urls.py
from django.urls import path 
from .views import *

app_name = 'orders'

urlpatterns = [
    path('created/', order_create, name='order_create'),
    path('direct/<int:item_id>/',direct_order, name='direct_order'),
    path('orders/', orders, name='order'),
    path('order-details/<int:id>', order_details, name='detail'),
    path('order-delete/<int:id>/delete', delete_order, name='delete_order'),
    path('payment/<int:order_id>/', initiate_payment, name='payment'),
    path('success/', payment_callback, name='payment_callback'),
]

Hivemind/cart/models.py
from django.db import models

# Create your models here.

Hivemind/jumia/models.py
from django.db import models
from user.models import User


class Categories(models.Model):        #these are categories for all products in database
    category_name = models.CharField(max_length=200)

    class Meta:
        ordering = ['category_name',]
        verbose_name_plural = 'Categories'
        
    def __str__(self):
        return self.category_name

class Type(models.Model):
    category = models.ForeignKey(Categories, related_name='type',on_delete=models.CASCADE, blank=True, null=True)
    name = models.CharField(max_length = 250)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits = 30, decimal_places=2)
    image = models.ImageField(upload_to='uploads/', null=True)
    is_available = models.BooleanField(default=True)
    product_by = models.ForeignKey(User,on_delete=models.CASCADE, blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name
    
   

Hivemind/orders/models.py
from django.db import models 
from jumia.models import Type
from user.models import User, Customer
from decimal import Decimal, ROUND_HALF_UP


class Order(models.Model):  
    user = models.ForeignKey(User, related_name='orders', on_delete=models.CASCADE, null=True)   
    address = models.CharField(max_length=250) 
    phone_number = models.CharField(max_length=20) 
    created = models.DateTimeField(auto_now_add=True)    
    updated = models.DateTimeField(auto_now=True)    
    paid = models.BooleanField(default=False)

    class Meta:        
        ordering = ['-created']        
        indexes = [           
             models.Index(fields=['-created']),        
             ]

    def __str__(self):        
        return f'Order {self.id}'
    
    def get_total_cost(self):        
        return sum(item.get_cost() for item in self.orders.all())
    
    def delivery(self):        
        total = self.get_total_cost()
        delivery_cost = total * Decimal('0.008')
        return delivery_cost.quantize(Decimal('0.01'),rounding=ROUND_HALF_UP)
    
    def cost(self):        
        return self.delivery() + self.get_total_cost()
    
        
class OrderItem(models.Model):    
    order = models.ForeignKey(Order,related_name='orders',on_delete=models.CASCADE)    
    product = models.ForeignKey(Type,related_name='items',on_delete=models.CASCADE)    
    price = models.DecimalField(max_digits=10,decimal_places=2)    
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)
    
    def get_cost(self):        
        return self.price * self.quantity
    
    
class Payment(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=20)
    transaction_id = models.CharField(max_length=100, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Payment'
        verbose_name_plural = 'Payments'
        
    def __str__(self):
        return f'Payment for order {self.order.id}.'
    

    

Hivemind/cart/forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):    
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int)
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

Hivemind/jumia/forms.py
from django import forms

class SearchForm(forms.Form):
    query = forms.CharField(label='Search')

Hivemind/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404 
from django.views.decorators.http import require_POST 
from jumia.models import Type 
from .cart import Cart 
from .forms import CartAddProductForm


@require_POST 
def cart_add(request, product_id):    
    cart = Cart(request)    
    product = get_object_or_404(Type, id=product_id)    
    form = CartAddProductForm(request.POST)    
    if form.is_valid():        
        cd = form.cleaned_data        
        cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])    
    return redirect('jumia:detail',product_id)

@require_POST 
def cart_remove(request, product_id):
        cart = Cart(request)    
        product = get_object_or_404(Type, id=product_id)    
        cart.remove(product)    
        return redirect('cart:cart_detail')

def cart_detail(request):    
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'],'update': True})
    return render(request, 'jumia/cart.html', {'cart': cart})



def cart_update(request, product_id):
    cart = Cart(request)
    quantity = int(request.POST.get('quantity', 1))
    product = get_object_or_404(Type, id=product_id)
    cart.add(product=product, quantity=quantity, override_quantity=True)
    return redirect('cart:cart_detail')

Hivemind/jumia/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render,get_object_or_404, redirect
from .models import Categories,Type
from django.http import HttpResponse
from user.decorators import customer_required,business_required
from django.db.models import Q
from cart.forms import CartAddProductForm
from .forms import SearchForm
from orders.forms import OrderCreateForm


def items(request):
    type = Type.objects.all()[:10]
    return render(request, 'jumia/item.html', {'type': type,})

def categories(request, id):
    category = get_object_or_404(Categories, pk=id)
    type = Type.objects.filter(category_id=id)
    return render(request, 'jumia/categories.html', {'type': type,
                                                     'category':category})


def detail(request, id):
    item = get_object_or_404(Type, pk=id)
    related_items = Type.objects.filter(category=item.category).exclude(pk=id)
    cart_product_form = CartAddProductForm()
    form = OrderCreateForm()

    return render(request, 'jumia/detail.html', {
        'item': item,
        'related_items': related_items,
        'cart_product_form':cart_product_form,
        'form':form,
    })


def search(request):
    if request.method == 'GET':
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            # Fix the lookup here
            results = Categories.objects.filter(category_name__icontains=query)
            results = Type.objects.filter(name__icontains=query)
            return render(request, 'jumia/search.html', {'results': results, 'query': query})
    else:
        form = SearchForm()
    return render(request, 'jumia/items.html', {'form': form})

Hivemind/jumia/templates/jumia/cart.html
{% extends 'jumia/base.html' %}
{% block title%} Cart {% endblock %}

{% load humanize %}
{% block content %}


{% if cart %}
<div class="lg:hidden">
    <div class="font-semibold mt-3">
        <h1 class="text-md">CART SUMMARY</h1>
    </div>
    <div class="flex justify-content-between border shadow-md p-2 mt-1 bg-white">
        <h1 class="text-md font-bold">Subtotal</h1>
        <p class="font-bold text-md">UGX {{ cart.get_total_price|intcomma }}</p>
    </div>
    <div>
        <h1 class="text-start text-md font-semibold pt-2">CART
            {% with total_items=cart|length %}
            {% if total_items > 0 %}
                ({{ total_items }})     
            {% else %}      
                (0)
            {% endif %}  
            {% endwith %} 
        </h1>
    </div>
    {% for item in cart %}        
    {% with product=item.product %}
    <div class="lg:hidden border p-3 mt-1 bg-white">
        <div class="flex flex-col lg:flex-row justify-between">
            <div class="flex inline-block">
                <img class="rounded-lg" src="{{product.image.url}}" alt="{{product.name}}" style="max-width: 100px;max-height: 100px">
                <div class="block">
                    <h1 class="text-md lg:text-lg px-3">{{product.name}} | <span class="text-sm"><a href="{% url 'jumia:category' product.category.id%}">{{product.category}}</a></span></h1>
                    <h1 class="text-sm lg:text-lg px-3">Quantity: {{item.quantity}}</h1>
                    <div class="block lg:hidden">
                        <h1 class="text-lg font-bold px-3">UGX {{product.price|intcomma}}</h1>
                    </div>
                </div>
            </div>
            <div class="hidden lg:flex lg:justify-end">
                <h1 class="text-lg font-semibold lg:text-xl mt-3">UGX {{product.price|intcomma}}</h1>
            </div>
        </div>                
        <div class="flex justify-content-between inline-block mt-2 mb-2">
            <form action="{% url 'cart:cart_remove' product.id %}" method="post">               
                <button type="submit" class="px-3 rounded btn btn-secondary"><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 inline-block mb-1">
                    <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
                  </svg>
                   Remove</button>
                {% csrf_token %}              
            </form>
            <div class="block lg:flex lg:items-center flex items-end lg:space-x-8 inline-block">
                <div class="quantity-controls inline-block flex justify-center items-center lg:mt-3">
                    <form action="{% url 'cart:cart_update' product.id %}" method="post" id="updateForm-{{ product.id }}">
                        {% csrf_token %}
                        <button type="button" class="btn btn-success rounded" onclick="decreaseQuantity('{{ product.id }}')">-</button>
                        <span id="quantityDisplay-{{ product.id }}" class="mx-4">{{ item.quantity }}</span>
                        <button type="button" class="btn btn-success rounded" onclick="increaseQuantity('{{ product.id }}')">+</button>
                        <input type="hidden" name="quantity" id="quantity-{{ product.id }}" value="{{ item.quantity }}">
                    </form>
                </div>                
            </div>
            </div>
        </div>
    </div>
    {% endwith %}      
    {% endfor %}
    <div class="lg:hidden">
        <a href="{% url 'orders:order_create' %}" class="btn btn-block text-xl btn-success my-3 py-2 lg:py-3 w-full">Checkout (UGX {{ cart.get_total_price|intcomma }})</a>
    </div>    
</div>


<div class="container-fluid">
    <div class="hidden lg:grid lg:grid-cols-12 gap-5 mt-4">
        <div class="lg:col-span-9 border shadow-md">
            <h1 class="text-start text-2xl font-bold p-3">Cart 
                {% with total_items=cart|length %}
                {% if total_items > 0 %}
                    ({{ total_items }})     
                {% else %}      
                    (0)
                {% endif %}  
                {% endwith %} 
            </h1>
            <hr class="w-full">
                {% for item in cart %}        
                    {% with product=item.product %}
                    <div class="p-3 flex flex-col lg:flex-row justify-between">
                        <div class="flex inline-block">
                            <img class="mt-4 rounded-lg" src="{{product.image.url}}" alt="{{product.name}}" style="max-width: 100px;max-height: 100px">
                            <div class="block">
                                <h1 class="text-md lg:text-lg mt-3 px-3">{{product.name}}</h1>
                                <h1 class="text-sm lg:text-sm px-3">{{product.category}}</h1>
                                <h1 class="text-sm lg:text-lg px-3">Quantity: {{item.quantity}}</h1>
                                <div class="block lg:hidden">
                                    <h1 class="text-lg font-bold px-3">UGX {{product.price|intcomma}}</h1>
                                </div>
                            </div>
                        </div>
                        <div class="hidden lg:flex lg:justify-end">
                            <h1 class="text-lg font-semibold lg:text-xl mt-3">UGX {{product.price|intcomma}}</h1>
                        </div>
                    </div>                
                    <div class="px-3 flex justify-content-between inline-block mb-2">
                        <form action="{% url 'cart:cart_remove' product.id %}" method="post">               
                            <button type="submit" class="px-3 rounded btn btn-secondary"><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 inline-block mb-1">
                                <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
                              </svg> Remove</button>
                            {% csrf_token %}              
                        </form>
                        <div class="block lg:flex lg:items-center flex items-end lg:space-x-8 inline-block">
                            <div class="quantity-controls inline-block flex justify-center items-center lg:mt-3">
                                <form action="{% url 'cart:cart_update' product.id %}" method="post" id="updateForm-{{ product.id }}">
                                    {% csrf_token %}
                                    <button type="button" class="btn btn-success rounded" onclick="decreaseQuantity('{{ product.id }}')">-</button>
                                    <span id="quantityDisplay-{{ product.id }}" class="mx-4">{{ item.quantity }}</span>
                                    <button type="button" class="btn btn-success rounded" onclick="increaseQuantity('{{ product.id }}')">+</button>
                                    <input type="hidden" name="quantity" id="quantity-{{ product.id }}" value="{{ item.quantity }}">
                                </form>
                            </div> 
                        </div>
                    </div>
                    {% endwith %}      
                {% endfor %}
        </div>
        <div class="hidden lg:block lg:col-span-3 lg:mt-4 border shadow-md p-3 h-48">
            <h1 class="text-start font-bold text-xl">CART SUMMARY</h1>
            <hr>
            <div class="flex justify-between p-3 font-semibold">
                <p class="text-xl">Total: </p>
                <h1 class="text-2xl">UGX {{ cart.get_total_price|intcomma }}</h1>
            </div>
            <hr>
            <a href="{% url 'orders:order_create' %}" class="btn btn-block rounded-lg text-xl btn-success my-3 py-2 lg:py-3 w-full">Checkout</a>
        </div>    
    </div>
</div>
{% else %}
    <div class="col-12 text-center font-mono mt-5">
        <h3 class="py-2 text-lg lg:text-2xl text-gray-700">Your Cart is empty!!</h3>
        <p class="text-sm lg:text-lg">Browse our categories and discover the best prosucts for you.</p>
        <a href="{% url 'jumia:items' %}" class="btn btn-block rounded-lg text-xl btn-success my-3 py-2 lg:py-3 w-full">Start shopping here.</a>
    </div>
{% endif %}

<script>
    function decreaseQuantity(productId) {
        var quantityDisplay = document.getElementById('quantityDisplay-' + productId);
        var quantityInput = document.getElementById('quantity-' + productId);
        var currentValue = parseInt(quantityDisplay.innerText);
        if (currentValue > 1) {
            quantityDisplay.innerText = currentValue - 1;
            quantityInput.value = currentValue - 1;
            document.getElementById('updateForm-' + productId).submit();  // Auto-submit form
        }
    }

    function increaseQuantity(productId) {
        var quantityDisplay = document.getElementById('quantityDisplay-' + productId);
        var quantityInput = document.getElementById('quantity-' + productId);
        var currentValue = parseInt(quantityDisplay.innerText);
        quantityDisplay.innerText = currentValue + 1;
        quantityInput.value = currentValue + 1;
        document.getElementById('updateForm-' + productId).submit();  // Auto-submit form
    }
</script>
{% endblock %}

Hivemind/jumia/templates/jumia/categories.html
{% extends 'jumia/base.html'%}
{% block title%} {{category.category_name}} {% endblock %}
{% block content %}
{% load humanize %}
<h1 class="text-justify-start pt-4 lg:py-4 text-xl lg:text-2xl lg:text-4xl font-bold">{{category.category_name}} Collections.</h1>
<hr>
<div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-3 gap-3">
    {% if type %}
        {% for item in type %}
        <div class="mt-2 relative group">
            <div class="rounded-2xl overflow-hidden shadow-md relative transform transition-transform duration-300 hover:scale-105 hover:shadow-xl">
              <a href="{% url 'jumia:detail' item.pk %}" class="transition ease-in-out duration-700">
                <img src="{{item.image.url}}" alt="" class="w-full h-48 object-cover mt-2 rounded-2xl transition-transform duration-300 group-hover:scale-110">
              </a>
            </div>
            <div class="mt-2">
              <h5 class="text-md font-bold text-gray-800">{{item.name}}</h5>
            </div>
          </div>
        {% endfor %}
    {% else %}
        <div class="col-span-full">
            <h1 class="text-center py-4 text-lg lg:text-3xl font-semibold">No available product for "{{ category.category_name }}" yet.</h1>
            <p class="text-center py-4 text-lg lg:text-2xl font-bold">Thanks for choosing us.</p>
        </div>
    {% endif %}
</div>
{% endblock %} 

Hivemind/jumia/templates/jumia/checkout.html
{% extends 'jumia/base.html' %}
{% block title %} Checkout {% endblock %}
{% load humanize %}
{% block content %}

<div class="row px-xl-5">
    <div class="col-lg-8 lg:mt-4">
        <div class="w-full mb-2 mx-auto rounded-xl">
            <div class="font-semibold mt-3 lg:mt-3">
                <h1 class="text-md">CUSTOMER DETAILS</h1>
            </div>
            <div class="flex justify-content-between border lg:rounded-xl lg:shadow-sm shadow-md p-2 mt-1 bg-white">
                <h1 class="text-md font-semibold">Name</h1>
                <p class="font-bold text-md">{{customer.first_name}} {{customer.last_name}}</p>
            </div>
            <div class="lg:hidden font-semibold mt-3">
                <h1 class="text-md">Order summary</h1>
            </div>
            <div class="border shadow-sm p-2 rounded-lg lg:rounded-xl mt-2 bg-white lg:hidden">
                <h1 class="flex justify-between font-semibold">Items Total: <span>UGX {{cart.get_total_price|intcomma}}</span></h1>
                <h1 class="flex justify-between font-semibold pt-2 pb-1">Delivery: <span>UGX {{cart.delivery|intcomma}}</span></h1>
                <hr>
                <h1 class="flex justify-between font-bold pt-3">Total: <span class="text-xl">UGX {{cart.cost|intcomma}}</span></h1>
            </div>
            <div class="border shadow-sm p-2 rounded-lg lg:rounded-xl mt-2 bg-white">
                <h1 class="text-xl font-semibold">Delivery Details</h1>
                <hr>

                <form action="{% url 'orders:order_create' %}" method="post" class="mt-3">
                    {% csrf_token %}
                    <div class="mb-3">
                        <label for="id_phone_number" class="inline-block mb-2">Mobile</label>
                        {{ form.phone_number }}
                    </div>

                    <div class="mb-3">
                        <label class="inline-block mb-2">Address</label>
                        {{form.address}}
                    </div>
                    {% if form.errors or form.non_field_errors %}
                        <div class="mb-3 p-3 bg-red-100 rounded-xl">
                            {% for field in form %}
                                {{ field.errors }}
                            {% endfor %}
                            {{ form.non_field_errors }}
                        </div>
                    {% endif %}

                    <button type="submit" class="btn btn-block btn-success rounded-xl my-3 py-2 lg:py-3 font-semibold">Confirm Order</button>
                </form>
            </div>
            <div class="lg:hidden">
                <h1 class="pt-2 font-semibold">Payment Method</h1>
                <h1 class="text-sm rounded-lg shadow-sm p-2 bg-white mt-2">!!!! Note that by confirming order, payment will be done on delivery.
                    Payment for the specific order will have to be intiated by our AGENT upon reaching specified delivery address.
                </h1>
            </div>
        </div>
    </div>

    <div class="col-lg-4 hidden lg:inline-block lg:mt-5">
        <div class="card border-secondary mb-5">
            <div class="card-header bg-blue-200 border-0">
                <h4 class="font-weight-semi-bold m-0">Order Total</h4>
            </div>
            <div class="card-body">
                <h5 class="font-weight-medium mb-3">Products</h5>
                {% for item in cart %}
                    <div class="d-flex justify-content-between">
                        <p class="font-weight-medium">{{ item.product.name }}</p>
                        <p>shs. {{ item.total_price|intcomma }}</p>
                    </div>
                {% endfor %}
                <hr class="mt-2">
                <div class="d-flex justify-content-between">
                    <p class="font-weight-medium">Delivery</p>
                    <p>UGX {{ cart.delivery|intcomma }}</p>
                </div>
            </div>
            <div class="card-footer border-secondary bg-transparent">
                <div class="d-flex justify-content-between mt-2">
                    <h5 class="font-weight-bold">Total</h5>
                    <h5 class="font-weight-bold">UGX {{ cart.cost|intcomma }}</h5>
                </div>
            </div>
        </div>
        <div class="hidden lg:block">
            <h1 class="font-semibold">Payment Method</h1>
            <h1 class="text-sm rounded-lg shadow-sm p-2 bg-white mt-2">!!!! Note that by confirming order, payment will be done on delivery.
                Payment for the specific order will have to be intiated by our AGENT upon reaching specified delivery address.
            </h1>
        </div>
    </div>
</div>


<script>
    function addressAutocomplete(inputElement, callback) {
    const MIN_ADDRESS_LENGTH = 3;
    const DEBOUNCE_DELAY = 300;

    let currentTimeout;
    let currentPromiseReject;
    let focusedItemIndex;

    inputElement.addEventListener("input", function(e) {
        const currentValue = this.value;
        closeDropDownList();

        if (currentTimeout) {
            clearTimeout(currentTimeout);
        }

        if (currentPromiseReject) {
            currentPromiseReject({
                canceled: true
            });
        }

        if (!currentValue || currentValue.length < MIN_ADDRESS_LENGTH) {
            return false;
        }

        currentTimeout = setTimeout(() => {
            currentTimeout = null;
            const promise = new Promise((resolve, reject) => {
                currentPromiseReject = reject;

                const apiKey = "a29d956305bd4b3288f90b68c5063650";
                const url = `https://api.geoapify.com/v1/geocode/autocomplete?text=${encodeURIComponent(currentValue)}&format=json&limit=5&apiKey=${apiKey}`;

                fetch(url)
                    .then(response => {
                        currentPromiseReject = null;
                        if (response.ok) {
                            response.json().then(data => resolve(data));
                        } else {
                            response.json().then(data => reject(data));
                        }
                    });
            });

            promise.then((data) => {
                const autocompleteItemsElement = document.createElement("div");
                autocompleteItemsElement.setAttribute("class", "autocomplete-items");
                inputElement.parentNode.appendChild(autocompleteItemsElement);

                data.results.forEach((result, index) => {
                    const itemElement = document.createElement("div");
                    itemElement.innerHTML = result.formatted;
                    autocompleteItemsElement.appendChild(itemElement);

                    itemElement.addEventListener("click", function(e) {
                        inputElement.value = data.results[index].formatted;
                        callback(data.results[index]);
                        closeDropDownList();
                    });
                });

            }, (err) => {
                if (!err.canceled) {
                    console.log(err);
                }
            });
        }, DEBOUNCE_DELAY);
    });

    inputElement.addEventListener("keydown", function(e) {
        const autocompleteItemsElement = inputElement.parentNode.querySelector(".autocomplete-items");
        if (autocompleteItemsElement) {
            const itemElements = autocompleteItemsElement.getElementsByTagName("div");
            if (e.keyCode == 40) {
                e.preventDefault();
                focusedItemIndex = focusedItemIndex !== itemElements.length - 1 ? focusedItemIndex + 1 : 0;
                setActive(itemElements, focusedItemIndex);
            } else if (e.keyCode == 38) {
                e.preventDefault();
                focusedItemIndex = focusedItemIndex !== 0 ? focusedItemIndex - 1 : focusedItemIndex = (itemElements.length - 1);
                setActive(itemElements, focusedItemIndex);
            } else if (e.keyCode == 13) {
                e.preventDefault();
                if (focusedItemIndex > -1) {
                    closeDropDownList();
                }
            }
        } else {
            if (e.keyCode == 40) {
                var event = document.createEvent('Event');
                event.initEvent('input', true, true);
                inputElement.dispatchEvent(event);
            }
        }
    });

    function setActive(items, index) {
        if (!items || !items.length) return false;

        for (var i = 0; i < items.length; i++) {
            items[i].classList.remove("autocomplete-active");
        }

        items[index].classList.add("autocomplete-active");
        inputElement.value = items[index].innerText;
        callback(currentItems[index]);
    }

    function closeDropDownList() {
        const autocompleteItemsElement = inputElement.parentNode.querySelector(".autocomplete-items");
        if (autocompleteItemsElement) {
            inputElement.parentNode.removeChild(autocompleteItemsElement);
        }
        focusedItemIndex = -1;
    }

    document.addEventListener("click", function(e) {
        if (e.target !== inputElement) {
            closeDropDownList();
        } else if (!inputElement.parentNode.querySelector(".autocomplete-items")) {
            var event = document.createEvent('Event');
            event.initEvent('input', true, true);
            inputElement.dispatchEvent(event);
        }
    });
}

addressAutocomplete(document.getElementById("address"), (data) => {
    console.log("Selected option: ", data);
    document.getElementById("address").value = data.formatted;
});

</script>
{% endblock %}