Hivemind/Hivemind/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jumia.urls')),
    path('inbox/', include('chart.urls')),
    path('cart/', include('cart.urls')),
    path('account/', include('user.urls')),
    path('order/', include('orders.urls')),
    path('business/', include('business.urls')),

    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Hivemind/cart/urls.py
from django.urls import path 
from . import views

app_name = 'cart'

urlpatterns = [    
    path('', views.cart_detail, name='cart_detail'),
    path('update/<int:product_id>', views.cart_update, name='cart_update'),    
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),    
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'), ]

Hivemind/jumia/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth.views import *
from .sitemap import StaticViewSitemap
from django.contrib.sitemaps.views import sitemap

sitemap_dict = {
    "static": StaticViewSitemap(),
}

app_name = 'jumia'

urlpatterns = [
    path('', items, name='items'),
    path('sitemap.xml', sitemap, {"sitemaps": sitemap_dict}, name="django.contrib.sitemaps.views.sitemap"),
    path('detail/<int:id>', detail, name='detail'),
    path('category/<int:id>', categories, name='category'),
    path('results/', search, name='search'),
]

Hivemind/orders/urls.py
from django.urls import path 
from .views import *

app_name = 'orders'

urlpatterns = [
    path('created/', order_create, name='order_create'),
    path('direct/<int:item_id>/',direct_order, name='direct_order'),
    path('orders/', orders, name='order'),
    path('order-details/<int:id>', order_details, name='detail'),
    path('order-delete/<int:id>/delete', delete_order, name='delete_order'),
    path('payment/<int:order_id>/', initiate_payment, name='payment'),
    path('success/', payment_callback, name='payment_callback'),
]

Hivemind/orders/models.py
from django.db import models 
from jumia.models import Type
from user.models import User, Customer
from decimal import Decimal, ROUND_HALF_UP


class Order(models.Model):  
    user = models.ForeignKey(User, related_name='orders', on_delete=models.CASCADE, null=True)   
    address = models.CharField(max_length=250) 
    phone_number = models.CharField(max_length=20) 
    created = models.DateTimeField(auto_now_add=True)    
    updated = models.DateTimeField(auto_now=True)    
    paid = models.BooleanField(default=False)

    class Meta:        
        ordering = ['-created']        
        indexes = [           
             models.Index(fields=['-created']),        
             ]

    def __str__(self):        
        return f'Order {self.id}'
    
    def get_total_cost(self):        
        return sum(item.get_cost() for item in self.orders.all())
    
    def delivery(self):        
        total = self.get_total_cost()
        delivery_cost = total * Decimal('0.008')
        return delivery_cost.quantize(Decimal('0.01'),rounding=ROUND_HALF_UP)
    
    def cost(self):        
        return self.delivery() + self.get_total_cost()
    
        
class OrderItem(models.Model):    
    order = models.ForeignKey(Order,related_name='orders',on_delete=models.CASCADE)    
    product = models.ForeignKey(Type,related_name='items',on_delete=models.CASCADE)    
    price = models.DecimalField(max_digits=10,decimal_places=2)    
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)
    
    def get_cost(self):        
        return self.price * self.quantity
    
    
class Payment(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    status = models.CharField(max_length=20)
    transaction_id = models.CharField(max_length=100, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Payment'
        verbose_name_plural = 'Payments'
        
    def __str__(self):
        return f'Payment for order {self.order.id}.'
    

    

Hivemind/orders/forms.py
from django import forms 
from .models import Order


class OrderCreateForm(forms.ModelForm):   
    class Meta:        
        model = Order        
        fields = ['address', 'phone_number']
        widgets = {
            'address': forms.TextInput(attrs={'id':'address','placeholder': 'Delivery address','class': 'w-full py-1 lg:py-2 px-3 rounded-lg lg:rounded-xl border border-red-900 autocomplete-container'}),
            'phone_number': forms.TextInput(attrs={'placeholder': 'Number will be used to intiate payments and calls.','class': 'w-full py-1 lg:py-22 px-3 rounded-lg lg:rounded-xl border border-red-900'}),
    
        }

Hivemind/orders/views.py
from django.shortcuts import render,get_object_or_404, redirect
from .models import OrderItem , Order
from django.http import HttpResponse, HttpResponseBadRequest
from .forms import OrderCreateForm
from cart.cart import Cart
from django.contrib.auth.decorators import login_required
from user.decorators import customer_required
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from twilio.rest import Client
import requests
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from .models import Payment, Order
from django.views.decorators.csrf import csrf_exempt
from django.http import JsonResponse
from .models import Payment
import re 
from user.models import Customer
from jumia.models import Type

@customer_required
def order_create(request):  
    user = request.user
    if user.is_authenticated:
        customer = Customer.objects.get(user=user)
        cart = Cart(request)
        if request.method == 'POST':      
            form = OrderCreateForm(request.POST)
            if form.is_valid():
                order = form.save(commit=False)
                order.user = request.user  
                order = form.save()     
                
                accountSID = 'ACe6d928ec56d8f0c7bce4f4301f592d45'
                authToken = '59519c547005d51047167550327627e5'
                twilioCli = Client(accountSID, authToken)
                myTwilioNumber = '+13345083970'
                myCellPhone = '+256761420297'
                twilioCli.messages.create(
                    body=f'Order was created by {customer.first_name} {customer.last_name}.\nFollow url to see details https://piusDev.pythonanywhere.com/business/orders/', 
                    from_=myTwilioNumber, 
                    to=myCellPhone
                    )
                
                for item in cart:                
                    OrderItem.objects.create(order=order, product=item['product'], price=item['price'],quantity=item['quantity'])        
                cart.clear()
            return render(request,'order/created.html', {'order': order})    
        else:        
            form = OrderCreateForm()    
        return render(request, 'jumia/checkout.html',{'cart': cart,'form': form,'customer':customer})

@login_required
def delete_order(request,id):
    delete_order = get_object_or_404(Order, id=id)

    if delete_order.user != request.user:
        return HttpResponseBadRequest("You do not have permission to delete this order.")

    if request.method == 'POST':
        delete_order.delete()
        return redirect('orders:order')
        
@customer_required
def orders(request):
    customer = Customer.objects.get(user=request.user)
    orders = Order.objects.filter(user=request.user)
    return render(request, 'order/orders.html', {'orders':orders,'customer':customer})

@customer_required
def order_details(request, id):
    orders = Order.objects.filter(id=id).filter(user=request.user).first()
    product = OrderItem.objects.filter(order=orders)
    return render(request, 'order/order_details.html', {'orders':orders, 'product':product})


def initiate_payment(request, order_id):
    phone_exp = re.compile(r'^(0)(\d{9})$')
    intl_phone_exp = re.compile(r'^\+256(\d{9})$')

    if request.method == 'POST':
        url = 'https://www.easypay.co.ug/api/'
        secret = 'd58fadc8a79ed090'
        client_id = '317caec39c6e050c'
        
        order = get_object_or_404(Order, id=order_id)
        amount = int(order.cost())
        
        # Format phone number
        phone_number = str(order.phone_number)
        
        match = phone_exp.match(phone_number)
        if match:
            phone_number = '+256' + match.group(2)  # Replace '0' with '+256'
        elif not intl_phone_exp.match(phone_number):
            return JsonResponse({'status': 'error', 'message': 'Invalid phone number format'})

        try:
            payload = {
                "username": client_id,
                "password": secret,
                "action": "mmdeposit",
                'amount': amount,
                'currency': 'UGX',
                'phone': phone_number,
                'reference': f'order_{order.id}'
            }
            headers = {
                'Content-Type': 'application/json'
            }

            response = requests.post(url, json=payload, headers=headers)

            data = response.json()
            if response.status_code == 200 and data.get('success'):
                Payment.objects.create(order=order, amount=amount, status='Pending', transaction_id=data['transaction_id'])
                return JsonResponse({'status': 'success', 'transaction_id': data['transaction_id']})
            else:
                error_message = data.get('errormsg', 'Unknown error occurred')
                return JsonResponse({'status': 'error', 'message': error_message})
        except Exception as e:
            return JsonResponse({'success': False, 'errormsg': str(e)})
    
    return JsonResponse({'success': False, 'errormsg': 'Invalid request method'})

    
@csrf_exempt
def payment_callback(request):
    if request.method == 'POST':
        data = request.json()
        transaction_id = data.get('transaction_id')
        status = data.get('status')

        payment = Payment.objects.get(transaction_id=transaction_id)
        payment.status = status
        payment.save()

        if status == 'Completed':
            # Update order status, notify customer, etc.
            pass

        return JsonResponse({'status': 'success'})

    return JsonResponse({'status': 'error'}, status=400)

@customer_required
def direct_order(request, item_id):
    item = get_object_or_404(Type, id=item_id)
    user = request.user
    if user.is_authenticated:
        customer = Customer.objects.get(user=user)
        if request.method == 'POST':
            form = OrderCreateForm(request.POST)
            if form.is_valid():
                order = form.save(commit=False)
                order.user = request.user  
                order.save()
                
                accountSID = 'ACe6d928ec56d8f0c7bce4f4301f592d45'
                authToken = '59519c547005d51047167550327627e5'
                twilioCli = Client(accountSID, authToken)
                myTwilioNumber = '+13345083970'
                myCellPhone = '+256761420297'
                twilioCli.messages.create(
                    body=f'Order was created by {customer.first_name} {customer.last_name}.\nFollow url to see details https://piusDev.pythonanywhere.com/business/orders/', 
                    from_=myTwilioNumber, 
                    to=myCellPhone
                                          )
                
                order_item = OrderItem(
                    order=order,
                    product=item,
                    price=item.price,
                    quantity=request.POST.get('quantity', 1)
                )
                order_item.save()
                return render(request,'order/created.html', {'order': order})
        else:
            form = OrderCreateForm()

        return render(request, 'jumia/detail.html', {'form': form, 'item': item})
    else:
        return redirect('user:login')

Hivemind/orders/templates/order/created.html
{% extends 'jumia/base.html' %}
{% block title%} products {% endblock %}

{% block content %}
<div class="shadow-md border rounded-lg mt-5 p-3 bg-white max-w-lg mx-auto flex flex-col text-start">
    <h2 class="lg:text-xl text-md font-semibold text-green-600 mb-1">
        <i class="fas fa-check-circle mr-2"></i>Order has been created successfully.
    </h2>
    <hr class="my-4 w-full">
    <p class="text-gray-700 lg:text-md text-sm">
        You'll be notified via a call when the product reaches you. Thank you!
    </p>
    <hr class="my-2 w-full">
    <p class="text-gray-700">
        Orders created can be viewed on the 
        <a href="{% url 'orders:order' %}" class="text-blue-600 hover:text-blue-800">orders page</a>.
    </p>
</div>
{% endblock %}

Hivemind/orders/templates/order/delete.html
{% extends 'jumia/base.html' %}

{% block title %}Orders{% endblock %}

{% block content %}
<form method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete this order?</p>
    <input type="submit" value="Yes, Delete">
</form>
{% endblock %}

Hivemind/orders/templates/order/order_details.html
{% extends 'jumia/base.html' %}

{% block title %} Orders {% endblock %}
{% load humanize %}
{% block content %}

<div class="lg:hidden">
  <h1 class="text-start text-lg font-semibold py-2 ml-2">Order summary</h1>
  <div class="border max-w-lg rounded-lg shadow-sm mr-2 bg-white">
    <div class="flex justify-between">
      <h1 class="text-sm font-semibold pt-2 ml-2">Date: </h1>
      <h1 class="text-sm font-semibold pt-2 mr-1">{{orders.created}}</h1>
    </div>
    <div class="flex justify-between">
      <h1 class="text-sm font-semibold ml-2">Phone Number: </h1>
      <h1 class="text-sm font-semibold mr-1">{{orders.phone_number}}</h1>
    </div>
    <div class="flex justify-between mb-2">
      <h1 class="text-sm font-semibold ml-2">{{orders.address}}</h1>
    </div>
  </div>
  <h1 class="text-start text-lg font-semibold py-2 ml-2">Products</h1>
  {% for item in product %}     
  <div class="border p-3 bg-white">
    <div class="flex flex-col lg:flex-row justify-between">
        <div class="flex inline-block">
            <img class="rounded-lg" src="{{item.product.image.url}}" alt="{{item.product.name}}" style="max-width: 100px;max-height: 100px">
            <div class="block">
                <h1 class="text-md lg:text-lg px-3">{{item.product.name}} | <span class="text-sm"><a href="{% url 'jumia:category' item.product.category.id%}">{{item.product.category}}</a></span></h1>
                <h1 class="text-sm lg:text-lg px-3">Quantity: {{item.quantity}}</h1>
                <div class="block">
                    <h1 class="text-lg font-semibold px-3">UGX {{item.get_cost|intcomma}}</h1>
                </div>
            </div>
        </div>
    </div>
  </div>    
  {% endfor %}
  <h1 class="text-start text-lg font-semibold py-2 ml-2">Totals</h1>
  <div class="border shadow-sm p-2 rounded-lg lg:rounded-xl bg-white lg:hidden">
    <h1 class="flex justify-between font-semibold">Items Total: <span>UGX {{orders.get_total_cost|intcomma}}</span></h1>
    <h1 class="flex justify-between font-semibold pt-2 pb-1">Delivery: <span>UGX {{orders.delivery|intcomma}}</span></h1>
    <hr>
    <h1 class="flex justify-between font-bold pt-3">Total: <span class="text-xl">UGX {{orders.cost|intcomma}}</span></h1>
  {% if orders.id %}
    <form id="paymentForm" action="{% url 'orders:payment' orders.id%}" method="post">
      {% csrf_token %}
      <button type="submit" id="submitButton" class="btn btn-block rounded-lg text-xl btn-success lg:mt-1 w-full">Pay For Order</button>
    </form>
    <form action="{% url 'orders:delete_order' orders.id %}" method="post" class="mt-2">
      {% csrf_token %}
      <button type="submit" class="btn btn-block btn-danger font-semibold rounded-lg"><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 inline-block mb-1">
        <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
      </svg> Delete Order</button>
    </form>
  {% endif %}

</div>
</div>

<div class="hidden lg:grid lg:grid-cols-12 gap-5 mt-4">
  <div class="lg:col-span-9 border shadow-md">
      <h1 class="text-start text-xl font-bold p-2">Ordered Products </h1>
      <hr class="w-full">
      <div class="grid grid-cols-3 gap-5 p-3">
          {% for item in product %}     
          <div class="flex flex-col lg:flex-row justify-between">
            <div class="flex inline-block">
                <img class="rounded-lg" src="{{item.product.image.url}}" alt="{{item.product.name}}" style="max-width: 100px;max-height: 100px">
                <div class="block pl-2">
                    <h1 class="text-md lg:text-lg">{{item.product.name}} | <span class="text-lg"><a href="{% url 'jumia:category' item.product.category.id%}">{{item.product.category}}</a></span></h1>
                    <h1 class="text-sm lg:text-lg">Quantity: {{item.quantity}}</h1>
                    <h1 class="text-lg font-semibold">UGX {{item.get_cost|intcomma}}</h1>
                </div>
            </div>
          </div>     
          {% endfor %}
      </div>
  </div>
  <div class="hidden lg:block lg:col-span-3 lg:mt-3 border shadow-md p-2 h-48">
      <h1 class="text-start font-bold text-xl">ORDER TOTALS</h1>
      <hr>
      <div class="flex justify-between font-semibold">
        <p class="text-lg">Items Total: </p>
        <h1 class="text-lg">UGX {{ orders.get_total_cost|intcomma }}</h1>
      </div>
      <div class="flex justify-between font-semibold">
        <p class="text-lg">Delivery: </p>
        <h1 class="text-lg">UGX {{ orders.delivery|intcomma }}</h1>
      </div>
      <hr class="p-1">
      <div class="flex justify-between mb-2">
          <p class="text-lg font-semibold">Total: </p>
          <h1 class="text-xl font-bold">UGX {{ orders.cost|intcomma }}</h1>
      </div>
      <form id="paymentForm" action="{% url 'orders:payment' orders.id%}" method="post">
        {% csrf_token %}
        <button type="submit" id="submitButton" class="btn btn-block rounded-lg text-xl btn-success lg:mt-1 w-full">Pay For Order</button>
      </form>
  </div>    
</div>

<div class="hidden lg:block">
  <div class="border max-w-lg rounded-lg shadow-sm mt-3 mr-2">
    <h1 class="text-start text-xl font-semibold pt-2 ml-2">Order summary</h1>
    <hr>
    <div class="flex justify-between">
      <h1 class="text-md font-semibold pt-2 ml-2">Date: </h1>
      <h1 class="text-sm font-semibold pt-3 mr-1">{{orders.created}}</h1>
    </div>
    <div class="flex justify-between">
      <h1 class="text-md font-semibold ml-2">Phone Number: </h1>
      <h1 class="text-sm font-semibold mr-1">{{orders.phone_number}}</h1>
    </div>
    <div class="flex justify-between mb-2">
      <h1 class="text-md font-semibold ml-2">Address: </h1>
      <h1 class="text-sm font-semibold">{{orders.address}}</h1>
    </div>
  </div>
  <div class="w-1/3 mt-2">
    <form action="{% url 'orders:delete_order' orders.id %}" method="post">
      {% csrf_token %}
      <button type="submit" class="btn btn-block btn-danger font-semibold rounded-lg"><svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 inline-block mb-1">
        <path stroke-linecap="round" stroke-linejoin="round" d="m14.74 9-.346 9m-4.788 0L9.26 9m9.968-3.21c.342.052.682.107 1.022.166m-1.022-.165L18.16 19.673a2.25 2.25 0 0 1-2.244 2.077H8.084a2.25 2.25 0 0 1-2.244-2.077L4.772 5.79m14.456 0a48.108 48.108 0 0 0-3.478-.397m-12 .562c.34-.059.68-.114 1.022-.165m0 0a48.11 48.11 0 0 1 3.478-.397m7.5 0v-.916c0-1.18-.91-2.164-2.09-2.201a51.964 51.964 0 0 0-3.32 0c-1.18.037-2.09 1.022-2.09 2.201v.916m7.5 0a48.667 48.667 0 0 0-7.5 0" />
      </svg> Delete Order</button>
    </form>
  </div>
</div>

<div id="paymentModal" class="modal justify-center align-center" tabindex="-1" role="dialog">
  <div class="modal-dialog modal-dialog-centered rounded-full" role="document">
    <div class="modal-content rounded-lg">
      <div class="modal-header">
        <h5 class="modal-title text-lg font-semibold">Payment Status</h5>
      </div>
      <div class="modal-body">
        <p id="paymentMessage">Processing your payment...</p>
        <div id="loadingSpinner" class="spinner-border text-success" role="status">
          <span class="sr-only">Loading...</span>
        </div>
      </div>
    </div>
  </div>
</div>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
$(document).ready(function() {
  $('#paymentForm').on('submit', function(e) {
    e.preventDefault();

    // Show the modal
    $('#paymentModal').modal('show');

    // Disable the form submission button to prevent multiple requests
    $('#submitButton').attr('disabled', true);

    // Send the AJAX request
    $.ajax({
      url: $(this).attr('action'),  // The payment URL
      method: 'POST',
      data: $(this).serialize(),
      success: function(response) {
        if (response.success) {
          // Update modal with success message
          $('#paymentMessage').text('Payment successful!');
          $('#loadingSpinner').hide();
        } else {
          // Handle errors
          $('#paymentMessage').text(response.errormsg || 'An error occurred.');
          $('#loadingSpinner').hide();
        }
      },
      error: function() {
        // Handle general errors
        $('#paymentMessage').text('An error occurred. Please try again.');
        $('#loadingSpinner').hide();
      },
      complete: function() {
        // Re-enable the form submission button
        $('#submitButton').attr('disabled', false);
      }
    });
  });
});
</script>
{% endblock %}

Hivemind/orders/templates/order/orders.html
{% extends 'jumia/base.html' %}

{% block title %}Your Orders{% endblock %}

{% block content %}
<div class="container py-4">
    <h1 class="flex text-start text-xl lg:text-4xl font-bold text-gray-800 mb-2">Your Orders</h1>
    <hr class="mb-8">

    <div class="row px-2">
        {% if orders %}
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {% for order in orders %}
            <a href="{% url 'orders:detail' order.id %}" class="block transition transform hover:scale-105 bg-white">
                <div class="border border-gray-100 shadow-md rounded-xl p-6 hover:bg-gray-50">
                    <div class="text-green-500 mb-1">
                        <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="inline-block w-5 mb-2">
                            <path stroke-linecap="round" stroke-linejoin="round" d="M11.35 3.836c-.065.21-.1.433-.1.664 0 .414.336.75.75.75h4.5a.75.75 0 0 0 .75-.75 2.25 2.25 0 0 0-.1-.664m-5.8 0A2.251 2.251 0 0 1 13.5 2.25H15c1.012 0 1.867.668 2.15 1.586m-5.8 0c-.376.023-.75.05-1.124.08C9.095 4.01 8.25 4.973 8.25 6.108V8.25m8.9-4.414c.376.023.75.05 1.124.08 1.131.094 1.976 1.057 1.976 2.192V16.5A2.25 2.25 0 0 1 18 18.75h-2.25m-7.5-10.5H4.875c-.621 0-1.125.504-1.125 1.125v11.25c0 .621.504 1.125 1.125 1.125h9.75c.621 0 1.125-.504 1.125-1.125V18.75m-7.5-10.5h6.375c.621 0 1.125.504 1.125 1.125v9.375m-8.25-3 1.5 1.5 3-3.75" />
                        </svg>
                        <h2 class="text-sm font-bold inline-block">Order ID: {{ order.id }}</h2>
                    </div>
                    <div class="text-sm text-gray-700">
                        <p><strong>Name:</strong> {{ customer.first_name }} {{ customer.last_name }}</p>
                        <p><strong>Date:</strong> {{ order.created }}</p>
                        <p><strong>Address:</strong> {{ order.address }}</p>
                    </div>
                </div>
            </a>
            {% endfor %}
        </div>
        {% else %}
        <div class="col-12 text-center font-mono">
            <h3 class="py-2 text-lg lg:text-2xl text-gray-700">No orders from you yet!!</h3>
            <h3 class="py-2 text-xl lg:text-2xl text-gray-700">
                <strong><a href="{% url 'jumia:items' %}" class="text-green-500 hover:text-green-700">Shop Here</a></strong>
            </h3>
            <h3 class="py-2 text-xl lg:text-2xl text-gray-700">Thank you for choosing us <i class="fas fa-heart text-red-500"></i></h3>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}