Hivemind/Hivemind/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('jumia.urls')),
    path('inbox/', include('chart.urls')),
    path('cart/', include('cart.urls')),
    path('account/', include('user.urls')),
    path('order/', include('orders.urls')),
    path('business/', include('business.urls')),

    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Hivemind/cart/urls.py
from django.urls import path 
from . import views

app_name = 'cart'

urlpatterns = [    
    path('', views.cart_detail, name='cart_detail'),
    path('update/<int:product_id>', views.cart_update, name='cart_update'),    
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),    
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'), ]

Hivemind/jumia/urls.py
from django.urls import path, include
from .views import *
from django.contrib.auth.views import *
from .sitemap import StaticViewSitemap
from django.contrib.sitemaps.views import sitemap

sitemap_dict = {
    "static": StaticViewSitemap(),
}

app_name = 'jumia'

urlpatterns = [
    path('', items, name='items'),
    path('sitemap.xml', sitemap, {"sitemaps": sitemap_dict}, name="django.contrib.sitemaps.views.sitemap"),
    path('detail/<int:id>', detail, name='detail'),
    path('category/<int:id>', categories, name='category'),
    path('results/', search, name='search'),
]

Hivemind/user/urls.py
from django.urls import path 
from .views import *
from django.contrib.auth import views as auth_views
from .forms import LoginForm


app_name = 'user'

urlpatterns = [
    path('signup/', CustomerSignUpView.as_view(), name='signup'),
    path("signup/business/",BusinessSignUpView.as_view(), name="reg"),
    path('login/',LoginView.as_view(), name='login'),
    path('logout/', Logout_view , name='logout'),
    path('sell/', Sell_details, name='sell_details' ),
]

   

Hivemind/user/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser
from django.utils import timezone

class User(AbstractUser):
    email = models.EmailField(unique=True)
    is_customer = models.BooleanField(default=False)
    is_business = models.BooleanField(default=False)

class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, related_name='customer')
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    created_at = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        """Returns a string representation of the business."""
        return self.first_name if self.first_name else 'not registered'

Hivemind/user/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django import forms
from jumia.models import Type, Categories
from .models import User, Customer
from django.db import transaction
from django.contrib.auth import get_user_model
from decimal import Decimal

User = get_user_model()

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your username',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))


class CustomerSignUpForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'First username','class': 'w-full py-4 px-6 rounded-xl'}))
    last_name = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Last username','class': 'w-full py-4 px-6 rounded-xl'}))
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Your username','class': 'w-full py-4 px-6 rounded-xl'}))
    email = forms.CharField(widget=forms.EmailInput(attrs={'placeholder': 'Your email address','class': 'w-full py-4 px-6 rounded-xl'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Your password','class': 'w-full py-4 px-6 rounded-xl'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Repeat password','class': 'w-full py-4 px-6 rounded-xl'}))

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    @transaction.atomic
    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_customer = True
        if commit:
            user.save()
        customer = Customer.objects.create(user=user, first_name=self.cleaned_data.get('first_name'), last_name=self.cleaned_data.get('last_name'),)
        return user

   

class DetailForm(forms.ModelForm):
    class Meta:
        model = Type
        fields = ['category','name','description','price','image']
        
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)  # Get the user from the kwargs
        super(DetailForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super().save(commit=False)
        if self.user:
            instance.product_by = self.user  # Set the product_by field to the logged-in user
        if commit:
            instance.save()
        return instance
    # def __init__(self, *args, **kwargs):
    #     user = kwargs.pop('user', None)
    #     super().__init__(*args, **kwargs)
    #     if user:
    #         self.fields['product_by'].queryset = User.objects.filter(pk=user.pk)

Hivemind/user/views.py
from django.shortcuts import render,redirect
from django.urls import reverse
from .forms import CustomerSignUpForm, DetailForm
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView
from .models import User
from .decorators import business_required
from business.forms import BusinessForm, BusinessSignUpForm
import django.contrib.auth.views as auth_views
from django.contrib.auth import login
from user.forms import LoginForm
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth import views as auth_views


class CustomerSignUpView(CreateView):
    model = User
    form_class = CustomerSignUpForm
    template_name = 'user/signup.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'customer'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        return redirect('user:login')

class BusinessSignUpView(CreateView):
    model = User
    form_class = BusinessSignUpForm
    template_name = 'bus/bus_reg.html'

    def get_context_data(self, **kwargs):
        kwargs['user_type'] = 'business'
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        return redirect('user:login')

def Logout_view(request):
    logout(request)
    return redirect('/')

class LoginView(auth_views.LoginView):
    form_class = LoginForm
    template_name = 'user/login.html'

    def get_context_data(self, **kwargs):
        return super().get_context_data(**kwargs)

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if next_url:
            return next_url
        else:
            user = self.request.user
            if user.is_authenticated:
                if user.is_customer:
                    return reverse('jumia:items')
                elif user.is_business:
                    return reverse('business:manage')
        return reverse('user:login')

@business_required
@login_required
def Sell_details(request):
    if request.method == 'POST':
        user = request.user
        form = DetailForm(request.POST, request.FILES,user=request.user)
        if form.is_valid():
            form.save()
            return redirect('business:manage')
    else:
        form = DetailForm()
    return render(request, 'user/sell_details.html', {'form':form})

Hivemind/user/templates/user/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{%block title%}{%endblock%} | Micheal & Yolanda</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="{%static 'reg/fonts/material-icon/css/material-design-iconic-font.min.css' %}">

    <!-- Main css -->
    <link rel="stylesheet" href="{%static 'reg/css/style.css' %}">
</head>
<body>
    <nav class="navbar-expand-lg sticky-top bg-light shadow-sm">
      
    </nav>
{% block content %}
{% endblock %}

 <!-- JS -->
 <script src="{%static 'reg/vendor/jquery/jquery.min.js' %}"></script>
 <script src="{%static 'reg/js/main.js' %}"></script>
</body>
</html>

Hivemind/user/templates/user/login.html
{% extends 'user/base.html' %}

{% block title %}Login {% endblock %}
{% load static %}
{% block content %}
<br>
<br>
<br>

<link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
<style>
    @media only screen and (max-width: 768px) {
    .login-image {
        display: none;
    }
}
.toggle-password {
    cursor: pointer;
    position: absolute;
    right: 10px;
    top: 10px;
    z-index: 2;
}

.form-group {
    position: relative;
}

</style>

<section class="sign-in">
    <div class="container">
        <div class="py-5 lg:flex">
            <div class="login-image hidden lg:block">
                <figure class=""><img src="{% static 'reg/images/signin-image.jpg' %}" alt="sign up image"></figure>
                <a href="{% url 'user:signup' %}" class="signup-image-link">Create an account</a>
            </div>            

            <div class="signin-form">
                <!-- <h2 class="text-start mb-4 text-xl">Login</h2> -->
                <a href="{% url 'jumia:items' %}" class="text-center">
                    <h1 class="text-2xl lg:text-3xl font-bold">Micheal <span class="text-green-500">& Yolanda</span></h1>
                    <h5 class="font-semibold text-sm">Fast Delivery Services</h5>
                </a>
                <form method="POST" class="pt-10" id="login-form" action="{% url 'user:login' %}?next={{ request.GET.next }}">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="your_name"><i class="zmdi zmdi-account material-icons-name"></i></label>
                        {{form.username}}
                    </div>
                    <div class="form-group">
                        <label for="your_pass"><i class="zmdi zmdi-lock"></i></label>
                        {{form.password}}
                        <span class="toggle-password">
                            <i class="zmdi zmdi-eye" id="toggle-password"></i>
                        </span>
                    </div>
                    <div class="form-group">
                        <input type="checkbox" name="remember-me" id="remember-me" class="agree-term" />
                        <label for="remember-me" class="label-agree-term"><span><span></span></span>Remember me</label>
                    </div>
                    <div class="form-group form-button">
                        <input type="submit" name="signin" id="signin" class="form-submit" value="Log in" />
                    </div>
                    {% if form.errors or form.non_field_errors %}
                    <div class="mb-3 p-3 bg-red-100 rounded-xl">
                        {% for field in form %}
                        {{ field.errors }}
                        {% endfor %}

                        {{ form.non_field_errors }}
                    </div>
                    {% endif %}
                </form>
                <div class="social-login">
                    <span class="social-label">Or login with</span>
                    <ul class="socials">
                        <li><a href="#"><i class="display-flex-center zmdi zmdi-facebook"></i></a></li>
                        <li><a href="#"><i class="display-flex-center zmdi zmdi-twitter"></i></a></li>
                        <li><a href="#"><i class="display-flex-center zmdi zmdi-google"></i></a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>
<script>
    document.getElementById('toggle-password').addEventListener('click', function () {
    const passwordField = document.querySelector('input[name="password"]');
    const type = passwordField.getAttribute('type') === 'password' ? 'text' : 'password';
    passwordField.setAttribute('type', type);

    // Toggle the icon
    this.classList.toggle('zmdi-eye');
    this.classList.toggle('zmdi-eye-off');
});

</script>

{% endblock %}

Hivemind/user/templates/user/logout.html
{% extends 'user/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Logged Out Successfully</h1>

    <a href=""><button class="py-4 px-8 text-lg bg-green-500 hover:bg-green-700 rounded-xl text-white">Login</button></a>
</div>
{% endblock %}

Hivemind/user/templates/user/sell_details.html
{% extends 'bus/board.html' %}

{% block title %}Sell{% endblock %}
{% load crispy_forms_tags %}

{% block content %}
<div class="w-full lg:w-1/2 my-6 mx-auto p-6 bg-gray-200  rounded-xl">
    <h1 class="mb-6 text-3xl lg:text-4xl text-center">Product details</h1>

    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}
        {{form|crispy }}
       <br>
        <button class="py-0 px-8 text-lg bg-green-500 hover:bg-green-700 rounded text-white">Sell</button>
    </form>
</div>
{% endblock %}

Hivemind/user/templates/user/signup.html
{% extends 'user/base.html' %}

{% block title %}Sign up{% endblock %}
{% load static %}
{% block content %}
<br>
<br>
<br>

<link href="https://unpkg.com/tailwindcss@^2/dist/tailwind.min.css" rel="stylesheet">
<style>
    @media only screen and (max-width: 768px) {
    .signin-image {
        display: none;
    }
}
.toggle-password {
    cursor: pointer;
    position: absolute;
    right: 10px;
    top: 10px;
    z-index: 2;
}

.form-group {
    position: relative;
}

</style>

<section class="signup">
  <div class="container">
      <div class="signup-content">
          <div class="signup-form">
              <a href="{% url 'jumia:items' %}" class="text-center">
                <h1 class="text-2xl lg:text-3xl font-bold">Micheal <span class="text-green-500">& Yolanda</span></h1>
                <h5 class="font-semibold text-sm">Fast Delivery Services</h5>
              </a>
              <form action="{% url 'user:signup' %}?next={{ request.GET.next }}" method="POST" class="pt-10" id="register-form">
                {% csrf_token %}
                <div class="form-group">
                  <label for="fname"><i class="zmdi zmdi-account material-icons-name"></i></label>
                  {{form.first_name}}
                </div>
                  <div class="form-group">
                    <label for="lname"><i class="zmdi zmdi-account material-icons-name"></i></label>
                    {{form.last_name}}
                  </div>
                  <div class="form-group">
                    <label for="lname"><i class="zmdi zmdi-account material-icons-name"></i></label>
                    {{form.username}}
                  </div>
                  <div class="form-group">
                      <label for="email"><i class="zmdi zmdi-email"></i></label>
                      {{form.email}}
                  </div>
                  <div class="form-group">
                    <label for="name"><i class="zmdi zmdi-phone"></i></label>
                    {{form.phone_number}}
                  </div>
                  <div class="form-group">
                      <label for="pass"><i class="zmdi zmdi-lock"></i></label>
                      {{form.password1}}
                      <span class="toggle-password">
                        <i class="zmdi zmdi-eye" id="toggle-password"></i>
                      </span>
                  </div>
                  <div class="form-group">
                      <label for="re-pass"><i class="zmdi zmdi-lock-outline"></i></label>
                      {{form.password2}}
                      <span class="toggle-password">
                        <i class="zmdi zmdi-eye" id="toggle-confirm-password"></i>
                      </span>
                  </div>
                  <div class="form-group">
                      <input type="checkbox" name="agree-term" id="agree-term" class="agree-term" />
                      <label for="agree-term" class="text-sm"><span><span></span></span>I agree all statements in  <a href="#" class="term-service">Terms of service</a></label>
                  </div>
                  <div class="form-group hidden lg:block">
                    <a href="#">I have an account</a>
                  </div>
                  <div class="form-group form-button">
                      <input type="submit" name="signup" id="signup" class="form-submit" value="SignUp"/>
                  </div>
                  <div class="form-group lg:hidden text-center text-lg">
                    <a href="{%url 'user:login' %}">I have an account</a>
                  </div>
              </form>
          </div>
          <div class="signin-image hidden lg:block">
              <figure><img src="{%static 'reg/images/signup-image.jpg' %}" alt="sing up image"></figure>
          </div>
      </div>
  </div>
</section>
<script>
  document.getElementById('toggle-password').addEventListener('click', function () {
    const passwordField = document.querySelector('input[name="password1"]');
    const type = passwordField.getAttribute('type') === 'password' ? 'text' : 'password';
    passwordField.setAttribute('type', type);

    // Toggle the icon
    this.classList.toggle('zmdi-eye');
    this.classList.toggle('zmdi-eye-off');
});
document.getElementById('toggle-confirm-password').addEventListener('click', function () {
    const passwordField = document.querySelector('input[name="password2"]');
    const type = passwordField.getAttribute('type') === 'password' ? 'text' : 'password';
    passwordField.setAttribute('type', type);

    // Toggle the icon
    this.classList.toggle('zmdi-eye');
    this.classList.toggle('zmdi-eye-off');
});
</script>
{% endblock %}